const OptionToolBarStyle = {
  optionToolBar: {
    flx: 'center-between',
    w: '100%',
    h: 40,
    bd: 'var(--white-100)',
    bb: '0.5px solid var(--white-0-89)',
    bs: '-1px 1px 4px var(--white-0-90)',
  },
  form_section: {
    flx: 'center-between',
    w: '80%',
  },
  field_btn: {
    flx: 'align-center',
    ml: 20,
    my: 4,
    px: 10,
    py: 4,
    fs: 12,
    fw: '600',
    cr: 'pointer',
    brs: 12,
    tn: 'background 0.5s ease',
    '&:hover': { bd: 'var(--white-0-81-32)' },
    '&.active': {
      bd: 'var(--b-79-96)',
      cr: 'var(--b-50)',
    },
  },
  txt: { ml: 3 },
  option_section: { flx: 'center-between' },

  icn_btn: {
    b: 'none',
    oe: 'none',
    p: 0,
    bd: 'none',
    brs: 8,
    w: 38,
    h: 33,
    flx: 'center',
    mr: 2,
    zx: 1,
    ow: 'hidden',
    cur: 'pointer',
    pn: 'relative',
    ':hover:not(:disabled, .active)': { cr: 'var(--b-53-13)' },
    ':focus-visible': { bs: '0 0 0 2px var(--b-50) inset' },
    '&.active': {
      bd: 'var(--b-79-96)',
      cr: 'var(--b-50)',
    },
  },
  border_right: {
    flx: 'center',
    w: '0.5px',
    h: 25,
    mx: 1,
    bd: 'var(--b-20-93)',
  },
  option_right: { flx: 'center' },
}

export default OptionToolBarStyle
